name: 'Bonfire extension QA'
author: 'Bonfire Networks'
description: 'Uses Bonfire extensions standard commands to build and test an extension'
inputs:
  elixir-version:
    description: 'The version of Elixir to be used for building and testing'
    required: false
    default: '1.17.2'
  otp-version:
    description: 'The version of OTP to be used for building and testing'
    required: false
    default: '27.1.2'
  db-startup-time:
    description: 'The number of seconds CI will wait before expecting the Postgres db to be running'
    required: false
    default: '10'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version }} # [Required] Define the Elixir version
        otp-version: ${{ inputs.otp-version }}       # [Required] Define the Erlang/OTP version

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Setup just
      run: sudo snap install --edge just --classic
      shell: bash

    - name: Get dependencies
      run: just deps-get
      shell: bash

    - name: Compile package
      run: just compile
      shell: bash

    - name: Run tests
      run: DB_STARTUP_TIME=${{ inputs.db-startup-time }} just test
      shell: bash
