name: 'Bonfire extension QA'
author: 'Bonfire Networks'
description: 'Uses Bonfire extensions standard commands to build and test an extension'
inputs:
  db-startup-time:
    description: 'The number of seconds CI will wait before expecting the Postgres db to be running'
    required: false
    default: '10'
  tx-token:
    description: 'Transifex API token'
    required: false
    default: ''
  github-token:
    description: 'GitHub token with permission to create branches and PRs. To use default GITHUB_TOKEN, make sure to grant write permissions to "contents" and "pull-requests" in your workflow file.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token || github.token }}
        fetch-depth: 0

    - id: setup
      name: Determine Elixir and OTP versions
      run: |
        ls -la && chmod +x tool-versions-to-env.sh
        # Run the script to extract versions and save to output
        ./tool-versions-to-env.sh 2 
      shell: bash

    - name: Add Prebuilt-MPR Repository
      run: |
        wget -qO - 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
        echo "deb [arch=all,$(dpkg --print-architecture) signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
        sudo apt update
      shell: bash

    - name: Install just
      run: sudo apt install just
      shell: bash

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.ERLANG_VERSION }}

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

    - name: Setup deps
      run: just deps-get && mkdir -p _build
      shell: bash
      env:
        MIX_ENV: test
        
    - name: Save deps cache
      uses: actions/cache/save@v4
      with:
        path: |
          deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ github.run_id }}

    - name: Check if TX is configured
      id: check_tx_enabled
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        if [ -d ".tx" ] && [ "${{ inputs.tx-token }}" != "" ]; then
          echo "tx_enabled=true" >> $GITHUB_OUTPUT
        else
          echo "tx_enabled=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Extract and push localisation strings
      if: ${{ steps.check_tx_enabled.outputs.tx_enabled == 'true' }}
      run: mix gettext.extract
      env:
        MIX_ENV: test
      shell: bash

    - name: Save build cache
      uses: actions/cache/save@v4
      with:
        path: |
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ github.run_id }}

    - name: Push source translations using transifex client
      if: ${{ steps.check_tx_enabled.outputs.tx_enabled == 'true' }}
      uses: transifex/cli-action@v2
      with:
        token: ${{ inputs.tx-token }}
        args: 'push'
        
    - name: Pull translations using transifex client
      if: ${{ steps.check_tx_enabled.outputs.tx_enabled == 'true' }}
      run: /tmp/tx/tx --token ${{ inputs.tx-token }} pull
      shell: bash
       
    - name: Check for translation changes
      if: ${{ steps.check_tx_enabled.outputs.tx_enabled == 'true' }}
      id: check_tx_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Setup translation branch
      if: ${{ steps.check_tx_changes.outputs.changes == 'true' }}
      run: |
        git config user.name "Transifex Bot"
        git config user.email "tx.bot@bonfire.cafe"
        
        # Setup authenticated remote if token is provided
        if [ -n "${{ inputs.github-token || github.token }}" ]; then
          REPO_URL="https://${{ inputs.github-token || github.token }}@github.com/${GITHUB_REPOSITORY}.git"
          git remote set-url origin "${REPO_URL}"
        fi

        BRANCH_NAME="update_translations"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        
        # Delete local branch if it exists
        git branch -D $BRANCH_NAME 2>/dev/null || true
        
        # Always create a fresh branch from current main
        git checkout -b $BRANCH_NAME
        
        # Will force push later to override remote branch if it exists
      shell: bash
      
    - name: Commit translation changes
      if: ${{ steps.check_tx_changes.outputs.changes == 'true' }}
      run: |
        git add .
        git commit -m "Update translations from Transifex"
        git push -f origin $BRANCH_NAME
      shell: bash
      
    - name: Check for existing PR
      if: ${{ steps.check_tx_changes.outputs.changes == 'true' }}
      uses: actions/github-script@v6
      id: check_pr
      with:
        script: |
          const prs = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:update_translations`,
            state: 'open'
          });
          return prs.data.length > 0 ? 'exists' : 'not_exists';
        result-encoding: string
      
    - name: Create Pull Request
      if: ${{ steps.check_tx_changes.outputs.changes == 'true' && steps.check_pr.outputs.result == 'not_exists' }}
      uses: peter-evans/create-pull-request@v7
      with:
        branch-token: ${{ inputs.github-token || github.token }}
        title: 'Update translations'
        body: 'This automated PR updates translations pulled from Transifex.'
        branch: ${{ env.BRANCH_NAME }}
        base: 'main'
 
    - name: Compile
      run: mix compile
      shell: bash
      env:
        MIX_ENV: test
            
    - name: Save build cache
      uses: actions/cache/save@v4
      with:
        path: |
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ github.run_id }}
          
    - name: Run tests
      run: DB_STARTUP_TIME=10 just test
      shell: bash
      env:
        MIX_ENV: test
              
    - name: Run linting
      run: just lint
      shell: bash
      env:
        MIX_ENV: test
        
